name: TamagoRPG
version: '${project.version}'
main: com.github.tsuoihito.tamagorpg.TamagoRPG
api-version: 1.19
depend: [ Multiverse-Core ]
commands:
  rpg:
    permission: tamagorpg.command
    usage: |
      /<command> save-world WORLD - Save the data for world WORLD.
      /<command> reset-world WORLD [DELAY] - Reset the data for WORLD after DELAY ticks.
permissions:
  tamagorpg.command:
    default: op
