name: TamagoRPG
version: '${project.version}'
main: net.nutchi.tamagorpg.TamagoRPG
api-version: 1.19
authors: [ Nutchi ]
depend: [ Multiverse-Core ]
commands:
  rpg:
    permission: tamagorpg.command.rpg
    usage: |
      /<command> save-world NAME
      /<command> reset-world NAME [DELAY]
  shared-location:
    permission: tamagorpg.commands.shared-location
    aliases: [ sl ]
permissions:
  tamagorpg.command.rpg:
    default: op
  tamagorpg.command.shared-location:
    default: op
