name: TamagoRPG
version: '${project.version}'
main: net.nutchi.tamagorpg.TamagoRPG
api-version: 1.19
authors: [ Nutchi ]
depend: [ Multiverse-Core ]
commands:
  rpg:
    permission: tamagorpg.command.rpg
    usage: |
      /<command> save-world NAME
      /<command> reset-world NAME [DELAY]
      /<command> list-tags
      /<command> list-scores
      /<command> search-tag NAME
      /<command> search-score NAME
permissions:
  tamagorpg.command.rpg:
    default: op
